openapi: 3.0.1

info:
  title: Rock - Paper - Scissors Game API
  description: 'This is API for play Rock, Paper and Scissors game'
  contact:
    email: jesus.urrutia@gmail.com
  version: 1.0.0

servers:
  - url: http://localhost:3000/api

tags:
  - name: game
    description: Create and play game

paths:
  /games:
    post:
      tags:
        - game
      summary: Create game
      description: Create a new game
      requestBody:
        description: Some description
        content:
          application/json:
            schema:
              properties:
                players:
                  type: array
                  minItems: 2
                  maxItems: 2
                  uniqueItems: true
                  items:
                    type: string
      responses:
        201:
          description: Game created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        400:
          description: Bad request
          content: {}

  /games/{game_id}:
    get:
      tags:
        - game
      summary: Get game
      description: Get game data
      parameters:
        - name: game_id
          in: path
          description: Game ID for retrieve
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Game object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        404:
          description: Game not found
          content: {}

    post:
      tags:
        - game
      summary: Create game round
      description: Create game round
      parameters:
        - name: game_id
          in: path
          description: Game ID
          required: true
          schema:
            type: integer
      requestBody:
        description: Some description
        content:
          application/json:
            schema:
              properties:
                movements:
                  type: array
                  items:
                    type: string
                    enum:
                      - rock
                      - paper
                      - scissors
                  minItems: 2
                  maxItems: 2
      responses:
        200:
          description: Game object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        403:
          description: Forbidden
          content: {}
        404:
          description: Game not found
          content: {}

components:
  schemas:
    Round:
      type: object
      properties:
        id:
          type: integer
          format: int64
        game_id:
          type: integer
          format: int64
        player_one_move:
          type: string
          enum:
            - rock
            - paper
            - scissors
        player_two_move:
          type: string
          enum:
            - rock
            - paper
            - scissors
        player_winner:
          type: integer
          format: int32
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Game:
      type: object
      properties:
        id:
          type: integer
          format: int64
        player_one:
          type: string
        player_two:
          type: string
        player_winner:
          type: integer
          format: int32
          nullable: true
        rounds:
          type: array
          items:
            $ref: '#/components/schemas/Round'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
